/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "FlowzWeb": {
      "type": "sst.aws.Nuxt"
      "url": string
    }
    "GoogleOAuthClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SessionPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TokenEncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TursoAuthToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}